language: objective-c
xcode_workspace: OXCMantle.xcworkspace
git:
  submodules: false
before_install:
  - pod install
script:
  - xcodebuild $XCODE_ACTION
      -workspace "$TRAVIS_XCODE_WORKSPACE"
      -scheme "$TRAVIS_XCODE_SCHEME"
      -sdk "$XCODE_SDK"
      -destination "$XCODE_DESTINATION"
      RUN_CLANG_STATIC_ANALYZER=NO
      | xcpretty
matrix:
  include:

    - xcode_scheme: "OXCMantle"
      osx_image: xcode8
      env:
        - XCODE_ACTION=test
        - XCODE_SDK=iphonesimulator
        - XCODE_DESTINATION="name=iPhone 7"
notifications:
  email:
        - 308325102@qq.com
    on_success: always
    on_failure: always
    
